name: ${project.name}
version: ${project.version}
main: com.gabrielhd.mines.PrivateMines
author: GabrielHD55
description: Private mines
api-version: 1.13
depend:
  - FastAsyncWorldEdit
  - WorldEdit
softdepend:
  - PlaceholderAPI
  - TokenEnchant
  - RevRankup
commands:
  mine:
    usage: /<command>
    aliases:
      - mines
